const orderActionTypes = {
  //create fetch
  // dispatch the cart items for CRUD operations
  DISPATCH_ORDER_ITEM_START: "DISPATCH_ORDER_ITEM_START",
  DISPATCH_ORDER_ITEM_SUCCESS: "DISPATCH_ORDER_ITEM_SUCCESS",
  DISPATCH_ORDER_ITEM_FAILURE: "DISPATCH_ORDER_ITEM_FAILURE",
  // fetch orders (admin)
  // admin

  GET_ADMIN_ORDERS_START: "GET_ADMIN_ORDERS_START",
  GET_ADMIN_ORDERS_SUCCESS: "GET_ADMIN_ORDERS_SUCCESS",
  GET_ADMIN_ORDERS_FAILURE: "GET_ADMIN_ORDERS_FAILURE",

  // update order by id (status)
  UPDATE_ORDER_STATUS_START: "UPDATE_ORDER_STATUS_START",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAILURE: "UPDATE_ORDER_STATUS_FAILURE",

  // fetch delivery boy list
  FETCH_DBOY_LIST_START: "FETCH_DBOY_LIST_START",
  FETCH_DBOY_LIST_SUCCESS: "FETCH_DBOY_LIST_SUCCESS",
  FETCH_DBOY_LIST_FAILURE: "FETCH_DBOY_LIST_FAILURE",

  // SEARCH ORDERS

  SEARCH_ORDER_START: "SEARCH_ORDER_START",
  SEARCH_ORDER_SUCCESS: "SEARCH_ORDER_SUCCESS",
  SEARCH_ORDER_FAILURE: "SEARCH_ORDER_FAILURE",

  CLEANUP_CREATED_ORDER: "CLEANUP_CREATED_ORDER",
  CLEANUP_ADMIN_ORDERLIST: "CLEANUP_ADMIN_ORDERLIST",
  CLEANUP_ORDER_STATUS: "CLEANUP_ORDER_STATUS",
  CLEANUP_DBOY_LIST: "CLEANUP_DBOY_LIST",
};
export default orderActionTypes;
