const employeeActionTypes = {
  // REGISTER EMPLOYEE
  REGISTER_EMPLOYEE_START: "REGISTER_EMPLOYEE_START",
  REGISTER_EMPLOYEE_SUCCESS: "REGISTER_EMPLOYEE_SUCCESS",
  REGISTER_EMPLOYEE_FAILURE: "REGISTER_EMPLOYEE_FAILURE",

  // FETCH EMPLOYEE RECORDS
  FETCH_EMPLOYEE_RECORDS_START: "FETCH_EMPLOYEE_RECORDS_START",
  FETCH_EMPLOYEE_RECORDS_SUCCESS: "FETCH_EMPLOYEE_RECORDS_SUCCESS",
  FETCH_EMPLOYEE_RECORDS_FAILURE: "FETCH_EMPLOYEE_RECORDS_FAILURE",


SET_EMP_ID:"SET_EMP_ID",

  // cleanup

  CLEANUP_REISTER_INFO: "CLEANUP_REISTER_INFO",
  CLAENUP_EMPLOYEE_RECORDS: "CLAENUP_EMPLOYEE_RECORDS",
};

export default employeeActionTypes;
