const productActionTypes = {
  // create product

  CREATE_PRODUCT_START: "CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",

  // fetch admin dashboard products summary
  FETCH_PRODUCTS_SUMMARY_START: "FETCH_PRODUCTS_SUMMARY_START",
  FETCH_PRODUCTS_SUMMARY_SUCCESS: "FETCH_PRODUCTS_SUMMARY_SUCCESS",
  FETCH_PRODUCTS_SUMMARY_FAILURE: "FETCH_PRODUCTS_SUMMARY_FAILURE",

  //get product info by id
  GET_PRODUCT_BY_ID_START: "GET_PRODUCT_BY_ID_START",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

  // select product by vendor reference // gettting aggregate

  GET_CATEGORY_VENDOR_START: "GET_CATEGORY_VENDOR_START",
  GET_CATEGORY_VENDOR_SUCCESS: "GET_CATEGORY_VENDOR_SUCCESS",
  GET_CATEGORY_VENDOR_FAILURE: "GET_CATEGORY_VENDOR_FAILURE",

  // get product list by key value

  GET_PRODUCT_LIST_START: "GET_PRODUCT_LIST_START",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_FAILURE: "GET_PRODUCT_LIST_FAILURE",

  // get productList by id
  GET_PRODUCT_LIST_BY_ID_START: "GET_PRODUCT_LIST_BY_ID_START",
  GET_PRODUCT_LIST_BY_ID_SUCCESS: "GET_PRODUCT_LIST_BY_ID_SUCCESS",
  GET_PRODUCT_LIST_BY_ID_FAILURE: "GET_PRODUCT_LIST_BY_ID_FAILURE",
  //
  //update product s
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  //create variants
  CREATE_VARIANTS_START: "CREATE_VARIANTS_START",
  CREATE_VARIANTS_SUCCESS: "CREATE_VARIANTS_SUCCESS",
  CREATE_VARIANTS_FAILURE: "CREATE_VARIANTS_FAILURE",

  // fetching variants by upn

  FETCH_VARIANTS_BY_UPN_START: "FETCH_VARIANTS_BY_UPN_START",
  FETCH_VARIANTS_BY_UPN_SUCCESS: "FETCH_VARIANTS_BY_UPN_SUCCESS",
  FETCH_VARIANTS_BY_UPN_FAILURE: "FETCH_VARIANTS_BY_UPN_FAILURE",

  // fetch varaint by sku
  FETCH_VARIANT_BY_SKU_START: "FETCH_VARIANT_BY_SKU_START",
  FETCH_VARIANT_BY_SKU_SUCCESS: "FETCH_VARIANT_BY_SKU_SUCCESS",
  FETCH_VARIANT_BY_SKU_FAILURE: "FETCH_VARIANT_BY_SKU_FAILURE",

  //updating variants by sku
  UPDATE_VARIANT_START: "UPDATE_VARIANT_START",
  UPDATE_VARIANT_SUCCESS: "UPDATE_VARIANT_SUCCESS",
  UPDATE_VARIANT_FAILURE: "UPDATE_VARIANT_FAILURE",

  // create description

  CREATE_DESCRIPTION_START: "CREATE_DESCRIPTION_START",
  CREATE_DESCRIPTION_SUCCESS: "CREATE_DESCRIPTION_SUCCESS",
  CREATE_DESCRIPTION_FAILURE: "CREATE_DESCRIPTION_FAILURE",

  // fetch description

  FETCH_DESCRIPTION_START: "FETCH_DESCRIPTION_START",
  FETCH_DESCRIPTION_SUCCESS: "FETCH_DESCRIPTION_SUCCESS",
  FETCH_DESCRIPTION_FAILURE: "FETCH_DESCRIPTION_FAILURE",

  // update description

  UPDATE_DESCRIPTION_START: "UPDATE_DESCRIPTION_START",
  UPDATE_DESCRIPTION_SUCCESS: "UPDATE_DESCRIPTION_SUCCESS",
  UPDATE_DESCRIPTION_FAILURE: "UPDATE_DESCRIPTION_FAILURE",

  // set search term for search
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  // set search Radius
  SET_SEARCH_RADIUS: "SET_SEARCH_RADIUS",

  // CLEAR SEARCH PRODUCT LIST
  CLEAR_SEARCH_LIST: "CLEAR_SEARCH_LIST",

  // get product search list

  GET_SEARCH_LIST_START: "GET_SEARCH_LIST_START",
  GET_SEARCH_LIST_SUCCESS: "GET_SEARCH_LIST_SUCCESS",
  GET_SEARCH_LIST_FAILURE: "GET_SEARCH_LIST_FAILURE",

  // get category list from the index
  GET_CATEGORY_LIST_START: "GET_CATEGORY_LIST_START",
  GET_CATEGORY_LIST_SUCCESS: "GET_CATEGORY_LIST_SUCCESS",
  GET_CATEGORY_LIST_FAILURE: "GET_CATEGORY_LIST_FAILURE",

  // load the subcategories

  GET_SUBCATEGORY_START: "GET_SUBCATEGORY_START",
  GET_SUBCATEGORY_SUCCESS: "GET_SUBCATEGORY_SUCCESS",
  GET_SUBCATEGORY_FAILURE: "GET_SUBCATEGORY_FAILURE",

  // load producList

  GET_USER_PRODUCT_LIST_START: "GET_USER_PRODUCT_LIST_START",
  GET_USER_PRODUCT_LIST_SUCCESS: "GET_USER_PRODUCT_LIST_SUCCESS",
  GET_USER_PRODUCT_LIST_FAILURE: "GET_USER_PRODUCT_LIST_FAILURE",

  // get featured product list
  GET_FEATURED_PRODUCT_LIST_START: "GET_FEATURED_PRODUCT_LIST_START",
  GET_FEATURED_PRODUCT_LIST_SUCCESS: "GET_FEATURED_PRODUCT_LIST_SUCCESS",
  GET_FEATURED_PRODUCT_LIST_FAILURE: "GET_FEATURED_PRODUCT_LIST_FAILURE",

  // search product

  SEARCH_PRODUCT_START: "SEARCH_PRODUCT_START",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",
  // SEARCH RECOMMENDATION
  SEARCH_RECOMMENDATION_SUCCESS: "SEARCH_RECOMMENDATION_SUCCESS",
  SEARCH_RECOMMENDATION_FAILURE: "SEARCH_RECOMMENDATION_FAILURE",

  // product state cleanup

  CLEANUP_CREATED_PRODUCT: "CLEANUP_CREATED_PRODUCT",
  CLEANUP_CREATED_DESC: "CLEANUP_CREATED_DESC",
  CLEANUP_UPDATED_DESC: "CLEANUP_UPDATED_DESC",

  CLEANUP_SUBCATEGORY: "CLEANUP_SUBCATEGORY",
  CLEANUP_USER_PRODUCTS: "CLEANUP_USER_PRODUCTS",
  CLEANUP_PRODUCT_UPDATE: "CLEANUP_PRODUCT_UPDATE",
  CLEANUP_SEARCH_LIST: "CLEANUP_SEARCH_LIST",
  PRODUCT_STATE_CLEANUP: "PRODUCT_STATE_CLEANUP",
  CLEANUP_VARIANT_CREATE: "CLEANUP_VARIANT_CREATE",
  CLEANUP_VARIANT_UPDATE: "CLEANUP_VARIANT_UPDATE",
  CLEANUP_RECOMMENDATIONS: "CLEANUP_RECOMMENDATIONS",
};
export default productActionTypes;
