const userActionTypes = {
  // google signin
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  GOOGLE_SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",

  // email signin

  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  EMAIL_SIGNIN_SUCCESS: "EMAIL_SIGNIN_SUCCESS",
  EMAIL_SIGNIN_FAILURE: "EMAIL_SIGNIN_FAILURE",

  // firebase email sign UP
  EMAIL_SIGNUP_START: "EMAIL_SIGNUP_START",
  EMAIL_SIGNUP_SUCCESS: "EMAIL_SIGNUP_SUCCESS",
  EMAIL_SIGNUP_FAILURE: "EMAIL_SIGNUP_FAILURE",

  //firebase signout start
  GOOGLE_SIGNOUT_START: "GOOGLE_SIGNOUT_START",
  GOOGLE_SIGNOUT_SUCCESS: "GOOGLE_SIGNOUT_SUCCESS",
  GOOGLE_SIGNOUT_FAILURE: "GOOGLE_SIGNOUT_FAILURE",

  // reset password

  RESET_PASSWORD_START: "RESET_PASSWORD_START",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  

  // SET DELIVERY LOCATION
  SET_DELIVERY_LOCATION:'SET_DELIVERY_LOCATION',
  

  SET_DELIVERY_LOCATION_FORM:'SET_DELIVERY_LOCATION_FORM',


  // set admin socket 
  SET_ADMIN_SOCKET:'SET_ADMIN_SOCKET',

  // clear user state

  CLEAR_USER_STATE: "CLEAR_USER_STATE",
};
export default userActionTypes;
